title: Rucha Shende
logo: "/images/photo-portfolio.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello there ğŸ‘‹ğŸ»
  I am CS graduate research student at Concordia University, Montreal advised by Dr. Sudhir Mudur and Dr. Tiberiu Popa. 
 
  Currently, I am finalizing thesis, aiming to graduate by the end of March 2024. 
  <br><br>
  Throughout my academic journey, I have been honing my skills in machine learning, deep learning and generative AI. 
  Additionally, I have two years of industry experience in software development.
  <br>


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
